version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_blockly
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     
      MYSQL_DATABASE: blockly_db            
    ports:
      - "3309:3306"                   
    volumes:
      - db_data:/var/lib/mysql      
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin_blockly
    restart: unless-stopped
    environment:
      PMA_HOST: db                       
      PMA_PORT: 3306
    ports:
      - "8085:80"                          
    depends_on:
      - db

volumes:
  db_data:
